# Generated by Django 2.0 on 2017-12-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
